# Load all the files
ggPm.At.roottip.crosssection <- dplyr::tibble(read.table("data-raw/ggPm.At.roottip.crosssection.txt",sep="\t",header=T))
ggPm.At.roottip.longitudinal <- dplyr::tibble(read.table("data-raw/ggPm.At.roottip.longitudinal.txt",sep="\t",header=T))
ggPm.At.3weekrosette.topview <- dplyr::tibble(read.table("data-raw/ggPm.At.3weekrosette.topview.txt",sep="\t",header=T))
ggPm.At.leafepidermis.topview <- dplyr::tibble(read.table("data-raw/ggPm.At.leafepidermis.topview.txt",sep="\t",header=T))
ggPm.At.leaf.crosssection <- dplyr::tibble(read.table("data-raw/ggPm.At.leaf.crosssection.txt",sep="\t",header=T))
ggPm.At.seed.devseries <- dplyr::tibble(read.table("data-raw/ggPm.At.seed.devseries.txt",sep="\t",header=T))
ggPm.At.earlyembryogenesis.devseries <- dplyr::tibble(read.table("data-raw/ggPm.At.earlyembryogenesis.devseries.txt",sep="\t",header=T))
ggPm.At.shootapex.longitudinal <- dplyr::tibble(read.table("data-raw/ggPm.At.shootapex.longitudinal.txt",sep="\t",header=T))
ggPm.At.inflorescencestem.crosssection <- dplyr::tibble(read.table("data-raw/ggPm.At.inflorescencestem.crosssection.txt",sep="\t",header=T))
ggPm.Sl.root.crosssection <- dplyr::tibble(read.table("data-raw/ggPm.Sl.root.crosssection.txt",sep="\t",header=T))
ggPm.At.leaf.topview <- dplyr::tibble(read.table("data-raw/ggPm.At.leaf.topview.txt",sep="\t",header=T))
ggPm.At.rootelong.longitudinal <- dplyr::tibble(read.table("data-raw/ggPm.At.rootelong.longitudinal.txt",sep="\t",header=T))
ggPm.At.rootmatur.crosssection <- dplyr::tibble(read.table("data-raw/ggPm.At.rootmatur.crosssection.txt",sep="\t",header=T))
ggPm.At.flower.diagram <- dplyr::tibble(read.table("data-raw/ggPm.At.flower.diagram.txt",sep="\t",header=T))
ggPm.At.lateralroot.devseries <- dplyr::tibble(read.table("data-raw/ggPm.At.lateralroot.devseries.txt",sep="\t",header=T))
ggPm.Ms.root.crosssection <- dplyr::tibble(read.table("data-raw/ggPm.Ms.root.crosssection.txt",sep="\t",header=T))
ggPm.At.seed.expression.sample <- dplyr::tibble(read.table("data-raw/ggPm.arabidopsis.seed.expression.sample.txt",sep="\t",header=T))
ggPm.tomatoatlas.expression.sample <- dplyr::tibble(read.table("data-raw/ggPm.tomatoatlas.expression.sample.txt",sep="\t",header=T))
ggPm.summary <- dplyr::tibble(read.csv("data-raw/ggPm.summary.csv"))

# Apply preprocessing...
# Save the cleaned data in the required R package location
usethis::use_data(ggPm.At.roottip.crosssection,overwrite=T)
usethis::use_data(ggPm.At.roottip.longitudinal,overwrite=T)
usethis::use_data(ggPm.At.3weekrosette.topview,overwrite=T)
usethis::use_data(ggPm.At.leafepidermis.topview,overwrite=T)
usethis::use_data(ggPm.At.leaf.crosssection,overwrite=T)
usethis::use_data(ggPm.At.seed.devseries,overwrite=T)
usethis::use_data(ggPm.At.earlyembryogenesis.devseries,overwrite=T)
usethis::use_data(ggPm.At.shootapex.longitudinal,overwrite=T)
usethis::use_data(ggPm.At.inflorescencestem.crosssection,overwrite=T)
usethis::use_data(ggPm.Sl.root.crosssection,overwrite=T)
usethis::use_data(ggPm.At.leaf.topview,overwrite=T)
usethis::use_data(ggPm.At.rootelong.longitudinal,overwrite=T)
usethis::use_data(ggPm.At.rootmatur.crosssection,overwrite=T)
usethis::use_data(ggPm.At.flower.diagram,overwrite=T)
usethis::use_data(ggPm.At.lateralroot.devseries,overwrite=T)
usethis::use_data(ggPm.Ms.root.crosssection,overwrite=T)
usethis::use_data(ggPm.At.seed.expression.sample,overwrite=T)
usethis::use_data(ggPm.tomatoatlas.expression.sample,overwrite=T)
usethis::use_data(ggPm.summary,overwrite=T)
